- name: Clone my config repo
  git:
    repo: https://github.com/mohenoo/Config.git
    dest: ~/Github/Config
    version: wsl2
    update: yes
    depth: 1
    force: yes

- name: Install tpm for tmux
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    depth: 1
    force: yes

- name: Install spacemacs for emacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
    version: develop
    depth: 1
    force: yes

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.8.0
    depth: 1
    force: yes

- name: Install apps with apt
  become: yes
  apt: 
    update_cache: yes
    name: ['subversion', 'thefuck', 'pipenv', 'neovim', 'tmux', 'tmuxinator', 'zsh', 'gpg', 'coreutils', 'curl', 'wget','aria2', 'emacs', 'build-essential' , 'zlib1g-dev', 'libncurses5-dev', 'libgdbm-dev', 'libnss3-dev', 'libssl-dev', 'libreadline-dev' ,'libffi-dev', 'libbz2-dev', 'libsqlite3-dev', 'silversearcher-ag', 'ripgrep', 'fd-find']
  # ignore_errors: yes

- name: ln my configs.
  file:
    src: '~/Github/Config/{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: 'zsh/.zshrc',dest: ~/.zshrc }
    - { src: 'tmux/.tmux.conf',dest: ~/.tmux.conf }
    - { src: 'nvim',dest: ~/.config/nvim }
    - { src: 'spacemacs', dest: ~/.spacemacs.d }
    - { src: 'aria2', dest: ~/.config/.aria2 }

- name: Config asdf
  shell: "{{ item }}"
  ignore_errors: yes
  loop:
    - 'asdf plugin add python'
    - 'asdf plugin add golang'
    - 'asdf plugin add nodejs'
    - 'asdf install golang latest'
    - 'asdf install python latest'
    - 'asdf install python 2.7.18'
    - "bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'"
    - 'asdf install nodejs latest'

- name: Install python package.
  pip:
    name: ['neovim']

     
