- name: Clone my config repo
  git:
    repo: https://github.com/mohenoo/Config.git
    dest: ~/Github/Config
    update: yes
    depth: 1
    force: yes

- name: Install tpm for tmux
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    depth: 1
    force: yes

- name: Install spacemacs for emacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
    version: develop
    depth: 1
    force: yes


- name: Tab homebrew repository
  homebrew_tap:
    name: ['railwaycat/emacsmacport','homebrew/cask-fonts']

- name: Install apps with homebrew
  homebrew: 
    name: ['svn', 'thefuck', 'asdf', 'pipenv', 'neovim', 'tmux', 'tmuxinator', 'starship', 'zsh', 'minikube', 'exa', 'bat', 'fd', 'ag', 'rg', 'gpg', 'coreutils', 'curl', 'wget','aria2', 'koekeishiya/formulae/yabai', 'koekeishiya/formulae/skhd']
    state: present

- name: Install emacs-mac with homebrew
  homebrew: 
    name: emacs-mac
    options: with-spacemacs-icon,with-no-title-bars
    state: present

- name: Install apps with homebrew_cask
  homebrew_cask: 
    name: ['alfred', 'google-chrome', 'kitty', 'spotify', 'openconnect-gui', 'feishu', 'notion', '1password', 'font-meslo-lg-nerd-font', 'font-fira-code-nerd-font', 'font-sauce-code-pro-nerd-font', 'avibrazil-rdm', 'dropbox']
    state: present

- name: mkdir .config
  file:
    path: ~/.config
    state: directory

- name: ln my configs.
  file:
    src: '~/Github/Config/{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: 'zsh/.zshrc',dest: ~/.zshrc }
    - { src: 'yabai/.yabairc',dest: ~/.yabairc }
    - { src: 'skhd/.skhdrc',dest: ~/.skhdrc }
    - { src: 'tmux/.tmux.conf',dest: ~/.tmux.conf }
    - { src: 'nvim',dest: ~/.config/nvim }
    - { src: 'spacemacs', dest: ~/.spacemacs.d }
    - { src: 'aria2', dest: ~/.config/.aria2 }
    - { src: 'rime-settings', dest: ~/Library/Rime }
    - { src: 'kitty', dest: ~/.config/kitty }

- name: Config yabai and skhd
  shell: "{{ item }}"
  ignore_errors: yes
  loop:
    - 'sudo yabai --install-sa'
    - 'brew services restart yabai'
    - 'brew services restart skhd'

- name: Config asdf
  shell: "{{ item }}"
  ignore_errors: yes
  loop:
    - 'asdf plugin add python'
    - 'asdf plugin add golang'
    - 'asdf plugin add nodejs'
    - 'asdf install golang latest'
    - 'asdf install python latest'
    - 'asdf install python 2.7.18'
    - "bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'"
    - 'asdf install nodejs latest'
    - 'asdf global python 2.7.18 `asdf latest python`'
    - 'asdf global golang `asdf latest golang`'
    - 'asdf global nodejs `asdf latest nodejs`'
    - 'compaudit | xargs chmod g-w'
    - 'source ~/.zshrc'
